### ISSUE TITLE
Hi, can you help me with the problem

### ISSUE THREAD

**Issue by royaalto** [SiyuanQi/yolo_object_detection#1]
when i catkin_make, I get this error, can you help me to fix it. thank you very much

roy@GIM:~/catkin_ws$ catkin_make
Base path: /home/roy/catkin_ws
Source space: /home/roy/catkin_ws/src
Build space: /home/roy/catkin_ws/build
Devel space: /home/roy/catkin_ws/devel
Install space: /home/roy/catkin_ws/install
####
####
-- Using CATKIN_DEVEL_PREFIX: /home/roy/catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/kinetic
-- This workspace overlays: /opt/ros/kinetic
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/roy/catkin_ws/build/test_results
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.6
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 1 packages in topological order:
-- ~~  - yolo_object_detection
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'yolo_object_detection'
-- ==> add_subdirectory(yolo_object_detection)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
CMake Warning at /home/roy/catkin_ws/build/yolo_object_detection/cmake/yolo_object_detection-genmsg.cmake:3 (message):
  Invoking generate_messages() without having added any message or service
  file before.

  You should either add add_message_files() and/or add_service_files() calls
  or remove the invocation of generate_messages().
Call Stack (most recent call first):
  /opt/ros/kinetic/share/genmsg/cmake/genmsg-extras.cmake:307 (include)
  yolo_object_detection/CMakeLists.txt:21 (generate_messages)

-- yolo_object_detection: 0 messages, 0 services
-- Configuring done
CMake Warning (dev) at yolo_object_detection/CMakeLists.txt:80 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "YoloObjDetect_generate_messages_cpp" of target
  "yolo" does not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /home/roy/catkin_ws/build
####
####
[  0%] Built target sensor_msgs_generate_messages_nodejs
[  0%] Built target sensor_msgs_generate_messages_lisp
[  0%] Built target sensor_msgs_generate_messages_py
[  1%] Building NVCC (Device) object yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_col2im_kernels.cu.o
[  2%] Building NVCC (Device) object yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_avgpool_layer_kernels.cu.o
[  2%] Built target sensor_msgs_generate_messages_cpp
[  2%] Built target sensor_msgs_generate_messages_eus
-- Removing /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/./YOLO_CUDA_generated_col2im_kernels.cu.o
[  3%] Building NVCC (Device) object yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_network_kernels.cu.o
-- Removing /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/./YOLO_CUDA_generated_avgpool_layer_kernels.cu.o
/usr/bin/cmake -E remove /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/./YOLO_CUDA_generated_col2im_kernels.cu.o
/usr/bin/cmake -E remove /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/./YOLO_CUDA_generated_avgpool_layer_kernels.cu.o
[  3%] Built target yolo_object_detection_generate_messages_nodejs
-- Generating dependency file: /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_col2im_kernels.cu.o.NVCC-depend
[  5%] Building NVCC (Device) object yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_activation_kernels.cu.o
-- Generating dependency file: /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_avgpool_layer_kernels.cu.o.NVCC-depend
-- Removing /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/./YOLO_CUDA_generated_network_kernels.cu.o
/usr/local/cuda-8.0/bin/nvcc -M -D__CUDACC__ /home/roy/catkin_ws/src/yolo_object_detection/src/col2im_kernels.cu -o /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_col2im_kernels.cu.o.NVCC-depend -ccbin /usr/bin/cc -m64 -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"yolo_object_detection\" -DROSCONSOLE_BACKEND_LOG4CXX -DYOLO_CUDA_EXPORTS -Xcompiler ,\"-Wall\",\"-Wfatal-errors\",\"-Ofast\",\"-DGPU\",\"-DCUDNN\",\"-DOPENCV\",\"-fPIC\",\"-g\" -gencode arch=compute_50,code=[sm_50,sm_50] -DNVCC -I/usr/local/cuda-8.0/include -I/home/roy/catkin_ws/src/yolo_object_detection/include -I/opt/ros/kinetic/include -I/opt/ros/kinetic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -I/opt/ros/kinetic/include/opencv-3.2.0-dev -I/opt/ros/kinetic/include/opencv-3.2.0-dev/opencv -I/usr/include -I/usr/local/cuda-8.0/include
/usr/local/cuda-8.0/bin/nvcc -M -D__CUDACC__ /home/roy/catkin_ws/src/yolo_object_detection/src/avgpool_layer_kernels.cu -o /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_avgpool_layer_kernels.cu.o.NVCC-depend -ccbin /usr/bin/cc -m64 -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"yolo_object_detection\" -DROSCONSOLE_BACKEND_LOG4CXX -DYOLO_CUDA_EXPORTS -Xcompiler ,\"-Wall\",\"-Wfatal-errors\",\"-Ofast\",\"-DGPU\",\"-DCUDNN\",\"-DOPENCV\",\"-fPIC\",\"-g\" -gencode arch=compute_50,code=[sm_50,sm_50] -DNVCC -I/usr/local/cuda-8.0/include -I/home/roy/catkin_ws/src/yolo_object_detection/include -I/opt/ros/kinetic/include -I/opt/ros/kinetic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -I/opt/ros/kinetic/include/opencv-3.2.0-dev -I/opt/ros/kinetic/include/opencv-3.2.0-dev/opencv -I/usr/include -I/usr/local/cuda-8.0/include
/usr/bin/cmake -E remove /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/./YOLO_CUDA_generated_network_kernels.cu.o
-- Removing /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/./YOLO_CUDA_generated_activation_kernels.cu.o
/usr/bin/cmake -E remove /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/./YOLO_CUDA_generated_activation_kernels.cu.o
-- Generating dependency file: /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_network_kernels.cu.o.NVCC-depend
-- Generating dependency file: /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_activation_kernels.cu.o.NVCC-depend
/usr/local/cuda-8.0/bin/nvcc -M -D__CUDACC__ /home/roy/catkin_ws/src/yolo_object_detection/src/network_kernels.cu -o /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_network_kernels.cu.o.NVCC-depend -ccbin /usr/bin/cc -m64 -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"yolo_object_detection\" -DROSCONSOLE_BACKEND_LOG4CXX -DYOLO_CUDA_EXPORTS -Xcompiler ,\"-Wall\",\"-Wfatal-errors\",\"-Ofast\",\"-DGPU\",\"-DCUDNN\",\"-DOPENCV\",\"-fPIC\",\"-g\" -gencode arch=compute_50,code=[sm_50,sm_50] -DNVCC -I/usr/local/cuda-8.0/include -I/home/roy/catkin_ws/src/yolo_object_detection/include -I/opt/ros/kinetic/include -I/opt/ros/kinetic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -I/opt/ros/kinetic/include/opencv-3.2.0-dev -I/opt/ros/kinetic/include/opencv-3.2.0-dev/opencv -I/usr/include -I/usr/local/cuda-8.0/include
/usr/local/cuda-8.0/bin/nvcc -M -D__CUDACC__ /home/roy/catkin_ws/src/yolo_object_detection/src/activation_kernels.cu -o /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_activation_kernels.cu.o.NVCC-depend -ccbin /usr/bin/cc -m64 -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"yolo_object_detection\" -DROSCONSOLE_BACKEND_LOG4CXX -DYOLO_CUDA_EXPORTS -Xcompiler ,\"-Wall\",\"-Wfatal-errors\",\"-Ofast\",\"-DGPU\",\"-DCUDNN\",\"-DOPENCV\",\"-fPIC\",\"-g\" -gencode arch=compute_50,code=[sm_50,sm_50] -DNVCC -I/usr/local/cuda-8.0/include -I/home/roy/catkin_ws/src/yolo_object_detection/include -I/opt/ros/kinetic/include -I/opt/ros/kinetic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -I/opt/ros/kinetic/include/opencv-3.2.0-dev -I/opt/ros/kinetic/include/opencv-3.2.0-dev/opencv -I/usr/include -I/usr/local/cuda-8.0/include
-- Generating temporary cmake readable file: /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_col2im_kernels.cu.o.depend.tmp
/usr/bin/cmake -D input_file:FILEPATH=/home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_col2im_kernels.cu.o.NVCC-depend -D output_file:FILEPATH=/home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_col2im_kernels.cu.o.depend.tmp -P /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake
-- Generating temporary cmake readable file: /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_activation_kernels.cu.o.depend.tmp
-- Generating temporary cmake readable file: /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_network_kernels.cu.o.depend.tmp
/usr/bin/cmake -D input_file:FILEPATH=/home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_activation_kernels.cu.o.NVCC-depend -D output_file:FILEPATH=/home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_activation_kernels.cu.o.depend.tmp -P /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake
-- Copy if different /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_col2im_kernels.cu.o.depend.tmp to /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_col2im_kernels.cu.o.depend
/usr/bin/cmake -D input_file:FILEPATH=/home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_network_kernels.cu.o.NVCC-depend -D output_file:FILEPATH=/home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_network_kernels.cu.o.depend.tmp -P /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake
/usr/bin/cmake -E copy_if_different /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_col2im_kernels.cu.o.depend.tmp /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_col2im_kernels.cu.o.depend
-- Generating temporary cmake readable file: /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_avgpool_layer_kernels.cu.o.depend.tmp
-- Copy if different /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_activation_kernels.cu.o.depend.tmp to /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_activation_kernels.cu.o.depend
-- Removing /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_col2im_kernels.cu.o.depend.tmp and /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_col2im_kernels.cu.o.NVCC-depend
/usr/bin/cmake -D input_file:FILEPATH=/home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_avgpool_layer_kernels.cu.o.NVCC-depend -D output_file:FILEPATH=/home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_avgpool_layer_kernels.cu.o.depend.tmp -P /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake
/usr/bin/cmake -E copy_if_different /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_activation_kernels.cu.o.depend.tmp /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_activation_kernels.cu.o.depend
/usr/bin/cmake -E remove /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_col2im_kernels.cu.o.depend.tmp /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_col2im_kernels.cu.o.NVCC-depend
-- Copy if different /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_network_kernels.cu.o.depend.tmp to /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_network_kernels.cu.o.depend
-- Generating /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/./YOLO_CUDA_generated_col2im_kernels.cu.o
-- Removing /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_activation_kernels.cu.o.depend.tmp and /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_activation_kernels.cu.o.NVCC-depend
/usr/bin/cmake -E copy_if_different /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_network_kernels.cu.o.depend.tmp /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_network_kernels.cu.o.depend
-- Copy if different /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_avgpool_layer_kernels.cu.o.depend.tmp to /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_avgpool_layer_kernels.cu.o.depend
/usr/bin/cmake -E remove /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_activation_kernels.cu.o.depend.tmp /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_activation_kernels.cu.o.NVCC-depend
/usr/local/cuda-8.0/bin/nvcc /home/roy/catkin_ws/src/yolo_object_detection/src/col2im_kernels.cu -c -o /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/./YOLO_CUDA_generated_col2im_kernels.cu.o -ccbin /usr/bin/cc -m64 -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"yolo_object_detection\" -DROSCONSOLE_BACKEND_LOG4CXX -DYOLO_CUDA_EXPORTS -Xcompiler ,\"-Wall\",\"-Wfatal-errors\",\"-Ofast\",\"-DGPU\",\"-DCUDNN\",\"-DOPENCV\",\"-fPIC\",\"-g\" -gencode arch=compute_50,code=[sm_50,sm_50] -DNVCC -I/usr/local/cuda-8.0/include -I/home/roy/catkin_ws/src/yolo_object_detection/include -I/opt/ros/kinetic/include -I/opt/ros/kinetic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -I/opt/ros/kinetic/include/opencv-3.2.0-dev -I/opt/ros/kinetic/include/opencv-3.2.0-dev/opencv -I/usr/include -I/usr/local/cuda-8.0/include
/usr/bin/cmake -E copy_if_different /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_avgpool_layer_kernels.cu.o.depend.tmp /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_avgpool_layer_kernels.cu.o.depend
-- Removing /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_network_kernels.cu.o.depend.tmp and /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_network_kernels.cu.o.NVCC-depend
-- Generating /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/./YOLO_CUDA_generated_activation_kernels.cu.o
/usr/bin/cmake -E remove /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_network_kernels.cu.o.depend.tmp /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_network_kernels.cu.o.NVCC-depend
-- Removing /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_avgpool_layer_kernels.cu.o.depend.tmp and /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_avgpool_layer_kernels.cu.o.NVCC-depend
/usr/local/cuda-8.0/bin/nvcc /home/roy/catkin_ws/src/yolo_object_detection/src/activation_kernels.cu -c -o /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/./YOLO_CUDA_generated_activation_kernels.cu.o -ccbin /usr/bin/cc -m64 -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"yolo_object_detection\" -DROSCONSOLE_BACKEND_LOG4CXX -DYOLO_CUDA_EXPORTS -Xcompiler ,\"-Wall\",\"-Wfatal-errors\",\"-Ofast\",\"-DGPU\",\"-DCUDNN\",\"-DOPENCV\",\"-fPIC\",\"-g\" -gencode arch=compute_50,code=[sm_50,sm_50] -DNVCC -I/usr/local/cuda-8.0/include -I/home/roy/catkin_ws/src/yolo_object_detection/include -I/opt/ros/kinetic/include -I/opt/ros/kinetic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -I/opt/ros/kinetic/include/opencv-3.2.0-dev -I/opt/ros/kinetic/include/opencv-3.2.0-dev/opencv -I/usr/include -I/usr/local/cuda-8.0/include
-- Generating /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/./YOLO_CUDA_generated_network_kernels.cu.o
/usr/bin/cmake -E remove /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_avgpool_layer_kernels.cu.o.depend.tmp /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_avgpool_layer_kernels.cu.o.NVCC-depend
/usr/local/cuda-8.0/bin/nvcc /home/roy/catkin_ws/src/yolo_object_detection/src/network_kernels.cu -c -o /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/./YOLO_CUDA_generated_network_kernels.cu.o -ccbin /usr/bin/cc -m64 -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"yolo_object_detection\" -DROSCONSOLE_BACKEND_LOG4CXX -DYOLO_CUDA_EXPORTS -Xcompiler ,\"-Wall\",\"-Wfatal-errors\",\"-Ofast\",\"-DGPU\",\"-DCUDNN\",\"-DOPENCV\",\"-fPIC\",\"-g\" -gencode arch=compute_50,code=[sm_50,sm_50] -DNVCC -I/usr/local/cuda-8.0/include -I/home/roy/catkin_ws/src/yolo_object_detection/include -I/opt/ros/kinetic/include -I/opt/ros/kinetic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -I/opt/ros/kinetic/include/opencv-3.2.0-dev -I/opt/ros/kinetic/include/opencv-3.2.0-dev/opencv -I/usr/include -I/usr/local/cuda-8.0/include
-- Generating /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/./YOLO_CUDA_generated_avgpool_layer_kernels.cu.o
/usr/local/cuda-8.0/bin/nvcc /home/roy/catkin_ws/src/yolo_object_detection/src/avgpool_layer_kernels.cu -c -o /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/./YOLO_CUDA_generated_avgpool_layer_kernels.cu.o -ccbin /usr/bin/cc -m64 -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"yolo_object_detection\" -DROSCONSOLE_BACKEND_LOG4CXX -DYOLO_CUDA_EXPORTS -Xcompiler ,\"-Wall\",\"-Wfatal-errors\",\"-Ofast\",\"-DGPU\",\"-DCUDNN\",\"-DOPENCV\",\"-fPIC\",\"-g\" -gencode arch=compute_50,code=[sm_50,sm_50] -DNVCC -I/usr/local/cuda-8.0/include -I/home/roy/catkin_ws/src/yolo_object_detection/include -I/opt/ros/kinetic/include -I/opt/ros/kinetic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -I/opt/ros/kinetic/include/opencv-3.2.0-dev -I/opt/ros/kinetic/include/opencv-3.2.0-dev/opencv -I/usr/include -I/usr/local/cuda-8.0/include
/home/roy/catkin_ws/src/yolo_object_detection/src/col2im_kernels.cu(52): error: identifier "BLOCK" is undefined

1 error detected in the compilation of "/tmp/tmpxft_00004cb3_00000000-7_col2im_kernels.cpp1.ii".
-- Removing /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/./YOLO_CUDA_generated_col2im_kernels.cu.o
/usr/bin/cmake -E remove /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/./YOLO_CUDA_generated_col2im_kernels.cu.o
CMake Error at YOLO_CUDA_generated_col2im_kernels.cu.o.cmake:266 (message):
  Error generating file
  /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/./YOLO_CUDA_generated_col2im_kernels.cu.o

yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/build.make:728: recipe for target 'yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_col2im_kernels.cu.o' failed
make[2]: *** [yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/YOLO_CUDA_generated_col2im_kernels.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[  5%] Built target yolo_object_detection_generate_messages_lisp
[  5%] Built target yolo_object_detection_generate_messages_py
[  6%] Built target yolo_object_detection_generate_messages_eus
[  6%] Built target yolo_object_detection_generate_messages_cpp
[  6%] Built target yolo_object_detection_generate_messages
Generated /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/./YOLO_CUDA_generated_activation_kernels.cu.o successfully.
Generated /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/./YOLO_CUDA_generated_avgpool_layer_kernels.cu.o successfully.
Generated /home/roy/catkin_ws/build/yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/src/./YOLO_CUDA_generated_network_kernels.cu.o successfully.
CMakeFiles/Makefile2:369: recipe for target 'yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/all' failed
make[1]: *** [yolo_object_detection/CMakeFiles/YOLO_CUDA.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed

**Comment by SiyuanQi-zz** [comment]
Hi, seems that the failure is related to cuda. Which GPU are you using? Did you set your cuda architecture version (sm_xx according to your GPU)?
